name: fonika_translate
description: >-
  Flutter translation, TTS, and ASR for African and world languages.
version: 0.2.0
homepage: https://229langues.bj
repository: https://github.com/Ronaldo-F-dev/fonika_translate
issue_tracker: https://github.com/Ronaldo-F-dev/fonika_translate/issues

topics:
  - translation
  - localization
  - tts
  - speech-recognition
  - african-languages

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  mime: ^2.0.0
  flutter_tts: ^4.2.5
  speech_to_text: ^7.4.0
  audioplayers: ^6.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
